# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: hello.proto for package 'go.micro.srv.greeter'

require 'grpc'
require 'hello_pb'

module Go
  module Micro
    module Srv
      module Greeter
        module Say
          class Service

            include GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'go.micro.srv.greeter.Say'

            rpc :Hello, Request, Response
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
